name = "vision"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[env.production]
name = "vision"

[[rules]]
type = "CompiledContentType"
globs = ["**/*.wasm"]
fallthrough = true
